version: "3.3"

networks:
  default:
    external:
      name: net-teleport

services:
  imega-teleport-commerceml2teleport:
    image: imegateleport/commerceml2teleport:${TAG}
    deploy:
      replicas: 1
