version: "3"

networks:
  default:
    external:
      name: net-findbed-app

services:
  findbed-app:
    image: registry.github.com/findbed/app:${TAG}
    environment:
      - COMMIT=${TAG}
      - LOG_LEVEL=debug
      - APP_HTTP_SERVER_HOST=0.0.0.0:8080
    deploy:
      replicas: 2
      restart_policy:
        delay: 10s
        max_attempts: 5
        window: 380s
