version: "3"

networks:
  default:
    external:
      name: net-findbed-app

volumes:
  findbed-volume:
    driver: local
  findbed-volume-2:
    driver: local

services:
  findbed-app:
    image: registry.github.com/findbed/app:${TAG}
    environment:
      - COMMIT=${TAG}
      - LOG_LEVEL=debug
      - APP_HTTP_SERVER_HOST=0.0.0.0:8080
    deploy:
      replicas: 2
      restart_policy:
        delay: 10s
        max_attempts: 5
        window: 380s

  findbed-mysql:
    image: mariadb:10.7.4
    environment:
      - MARIADB_ROOT_PASSWORD=qwerty
    volumes:
      - findbed-volume:/var/lib/mysql

  findbed-zinc:
    image: public.ecr.aws/zinclabs/zinc:0.3.5
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=123
    volumes:
      - findbed-volume-2:/data
