version: "3.3"

networks:
  net-deployer:
    external: true
  net-teleport:
    external: true
  esnet:
    external: true

services:
  imega-deploy-balancer:
    image: imegadeploy/balancer:${TAG}
    networks:
      - net-deployer
      - net-teleport
      - esnet
    ports:
      - "80:80"
    deploy:
      replicas: 1
