version: "3.3"

networks:
  net-deployer:
    external: true
  net-teleport:
    external: true
  esnet:
    external: true
  net-imega-iul:
    external: true
  net-imega-pbcode:
    external: true
  net-findbed-app:
    external: true

services:
  imega-deploy-balancer:
    image: imegadeploy/balancer:${TAG}
    networks:
      - net-deployer
      - net-teleport
      - net-imega-iul
      - net-imega-pbcode
      - net-findbed-app
      - esnet
    ports:
      - "80:80"
    deploy:
      replicas: 1
