version: "3.3"

networks:
  default:
    external:
      name: net-teleport

services:
  teleport-server:
    image: imegateleport/teleport-server:${TAG}
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwerty
      - MYSQL_HOST=imega-teleport-db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=stock
      - RSA_PUBLIC_KEY_FILE=/run/secrets/imega-teleport.public.key
      - RSA_PRIVATE_KEY_FILE=/run/secrets/imega-teleport.private.key
    secrets:
      - imega-teleport.private.key
      - imega-teleport.public.key
    deploy:
      replicas: 1

secrets:
  imega-teleport.private.key:
    external: true
  imega-teleport.public.key:
    external: true
