version: "3"

networks:
  default:
    external:
      name: net-imega-iul

services:
  imega-iul:
    image: imega/iul:${TAG}
    deploy:
      replicas: 2
      restart_policy:
        delay: 10s
        max_attempts: 5
        window: 380s
