version: "3.3"

networks:
  default:
    external:
      name: net-teleport

volumes:
  teleport-storage:
    external: true

services:
  imega-teleport-1s-receiver:
    image: imegateleport/1s-receiver:${TAG}
    environment:
      - FILE_LIMIT=1048576
    volumes:
      - teleport-storage:/data
    deploy:
      replicas: 1
