version: "3.3"

networks:
  default:
    external:
      name: net-teleport

volumes:
  teleport-db:
    external: true
  teleport-db-sql:
    external: true

services:
  imega-teleport-db:
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_DATABASE=teleport
    volumes:
      - teleport-db-sql:/docker-entrypoint-initdb.d
      - teleport-db:/var/lib/mysql
    deploy:
      replicas: 1
